[platformio]
core_dir = ../../../.platformio-home
default_envs = m5stack-core-gray

[env:m5stack-core-gray]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = huge_app.csv
build_flags =
  -pipe
  -D BLE_MIDI_DEVICE_NAME='"M5 Gray AMY Dual"'
lib_extra_dirs =
  ../../packages
lib_deps =
  firmware-contracts=file:///home/fcz/dev/m5stick/embedded-music-experiments
  monophonic-instrument=file:///home/fcz/dev/m5stick/monophonic-instrument/packages/monophonic-instrument
  fcz2/ble-midi-input@0.3.0
  m5stack/M5Unified@0.2.17
  amy=https://github.com/shorepine/amy.git#1.2.108
lib_ignore =
  ArduinoBLE
  Arduino_SpiNINA
