[platformio]
core_dir = ../../../.platformio-home
default_envs = m5stack-core-gray

[env:m5stack-core-gray]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_build.partitions = huge_app.csv
build_flags =
  -pipe
lib_extra_dirs =
  ../../packages
lib_deps =
  monophonic-instrument=https://github.com/fczuardi/monophonic-instrument.git#8159a694c086
  m5stack/M5Unified@0.2.17
  amy=https://github.com/shorepine/amy.git#1.2.108
