[platformio]
core_dir = ../../../../.platformio-home

[env:m5stack-core-gray]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-core-esp32
framework = arduino
board_build.partitions = huge_app.csv
lib_deps =
  amy-synth-m5=file://../../../packages/amy-synth-m5
