[platformio]
core_dir = ../../../.platformio-home
default_envs = native

[env:native]
platform = native
lib_deps = fcz2/step-trigger@>=0.1.0
test_framework = unity
test_build_src = false
build_flags =
  -I include
